### ISSUE TITLE
Not animating, deploy a demo?

### ISSUE THREAD

**Issue by crazy4groovy** [browniefed/react-flip-ticker#3]
I'm unable to see the <Ticker /> component animate its value.

Do you have a live example you can deploy/demo?

**Comment by browniefed** [comment]
Here is a demo https://codesandbox.io/s/k33p3nqwv5

**Comment by crazy4groovy** [comment]
Thanks!

Aside from the animation issue I was facing on my page, I also saw a padding issue similar to this:

https://codesandbox.io/s/rrqyyj3zno

**Comment by browniefed** [comment]
Yeah I should fix that.

**Comment by crazy4groovy** [comment]
Cheers :+1: It's a good component, I think I'll use it in a few spots.
